### ISSUE TITLE
Move docs to __docs__ and annotations to __annotations__

### ISSUE THREAD

**Issue by medanisjbara** [ankaboot-source/openweb-proxy#5]
https://docs.python.org/3/howto/annotations.html
https://peps.python.org/pep-0257/

**Comment by baderdean** [comment]
About doc string, it's on top of the module in __about__.py (newer convention)

**Comment by maleksal** [comment]
@baderdean @medanisjbara  

I didn't understand the part about moving `annotations to __annotations__`
